-- V26 already added DATA_UPDATE_TYPE, PREV_GAME_BIZ_TYPE, CULTURAL_BIZ_TYPE.
-- Keep this version as a no-op so fresh databases can migrate past V27.
ALTER TABLE dvd_stores MODIFY COLUMN DATA_UPDATE_TYPE VARCHAR(20) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN PREV_GAME_BIZ_TYPE VARCHAR(500) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN CULTURAL_BIZ_TYPE VARCHAR(200) NULL;
