-- 찜 허브: 메모·일정·태그·정렬
ALTER TABLE user_movie_likes
    ADD COLUMN MEMO VARCHAR(500) NULL COMMENT '여행 메모',
    ADD COLUMN PLANNED_DATE DATE NULL COMMENT '방문 예정일',
    ADD COLUMN TAGS_JSON VARCHAR(1000) NULL COMMENT 'JSON array of tag strings',
    ADD COLUMN SORT_ORDER INT NULL DEFAULT 0 COMMENT '사용자 정렬';

CREATE TABLE IF NOT EXISTS user_favorite_visits (
    USER_ID     VARCHAR(255) NOT NULL,
    VISIT_KEY   VARCHAR(512) NOT NULL COMMENT 'movie:ct:name:areaCode 등',
    VISITED_AT  DATETIME     NOT NULL,
    CREATED_AT  DATETIME     NOT NULL,
    CREATED_BY  VARCHAR(50)  NOT NULL,
    MODIFIED_AT DATETIME     NOT NULL,
    MODIFIED_BY VARCHAR(50)  NOT NULL,
    PRIMARY KEY (USER_ID, VISIT_KEY)
);

CREATE TABLE IF NOT EXISTS user_favorite_shares (
    SHARE_ID      VARCHAR(255) NOT NULL,
    USER_ID       VARCHAR(255) NOT NULL,
    SHARE_TOKEN   VARCHAR(64)  NOT NULL,
    PAYLOAD_JSON  MEDIUMTEXT   NOT NULL,
    CREATED_AT    DATETIME     NOT NULL,
    CREATED_BY    VARCHAR(50)  NOT NULL,
    MODIFIED_AT   DATETIME     NOT NULL,
    MODIFIED_BY   VARCHAR(50)  NOT NULL,
    EXPIRES_AT    DATETIME     NULL,
    PRIMARY KEY (SHARE_ID),
    UNIQUE KEY uk_share_token (SHARE_TOKEN)
);

CREATE TABLE IF NOT EXISTS user_travel_favorites (
    TRAVEL_FAV_ID  VARCHAR(255) NOT NULL,
    USER_ID        VARCHAR(255) NOT NULL,
    ITEM_TYPE      VARCHAR(32)  NOT NULL COMMENT 'medical|camping|custom',
    ITEM_ID        VARCHAR(255) NOT NULL,
    SNAPSHOT_JSON  TEXT         NULL,
    CREATED_AT     DATETIME     NOT NULL,
    CREATED_BY     VARCHAR(50)  NOT NULL,
    MODIFIED_AT    DATETIME     NOT NULL,
    MODIFIED_BY    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (TRAVEL_FAV_ID),
    UNIQUE KEY uk_user_travel_item (USER_ID, ITEM_TYPE, ITEM_ID)
);
