ALTER TABLE movies ADD COLUMN MOVIE_NAME_JA VARCHAR(500);
ALTER TABLE movies ADD COLUMN OVERVIEW_JA TEXT;
ALTER TABLE movies ADD COLUMN TAGLINE_JA VARCHAR(500);
ALTER TABLE movies ADD COLUMN POSTER_PATH_JA VARCHAR(500);
ALTER TABLE movies ADD COLUMN BACKDROP_PATH_JA VARCHAR(500);
