ALTER TABLE movies ADD COLUMN MOVIE_NAME_ZH VARCHAR(500);
ALTER TABLE movies ADD COLUMN OVERVIEW_ZH TEXT;
ALTER TABLE movies ADD COLUMN TAGLINE_ZH VARCHAR(500);
ALTER TABLE movies ADD COLUMN POSTER_PATH_ZH VARCHAR(500);
ALTER TABLE movies ADD COLUMN BACKDROP_PATH_ZH VARCHAR(500);
