ALTER TABLE movies ADD COLUMN MOVIE_NAME_NE VARCHAR(500);
ALTER TABLE movies ADD COLUMN OVERVIEW_NE TEXT;
ALTER TABLE movies ADD COLUMN TAGLINE_NE VARCHAR(500);
ALTER TABLE movies ADD COLUMN POSTER_PATH_NE VARCHAR(500);
ALTER TABLE movies ADD COLUMN BACKDROP_PATH_NE VARCHAR(500);
