-- Portuguese copy must be TEXT. movies already has EN/JA/ZH/NE VARCHAR(500) fields,
-- so another VARCHAR(500) hits MySQL's 65535 in-row limit (error 1118).
-- The first deploy may have added some PT VARCHAR columns before BACKDROP_PATH_PT failed.

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'movies' AND COLUMN_NAME = 'MOVIE_NAME_PT') = 0,
  'ALTER TABLE movies ADD COLUMN MOVIE_NAME_PT TEXT',
  'ALTER TABLE movies MODIFY COLUMN MOVIE_NAME_PT TEXT'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'movies' AND COLUMN_NAME = 'OVERVIEW_PT') = 0,
  'ALTER TABLE movies ADD COLUMN OVERVIEW_PT TEXT',
  'ALTER TABLE movies MODIFY COLUMN OVERVIEW_PT TEXT'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'movies' AND COLUMN_NAME = 'TAGLINE_PT') = 0,
  'ALTER TABLE movies ADD COLUMN TAGLINE_PT TEXT',
  'ALTER TABLE movies MODIFY COLUMN TAGLINE_PT TEXT'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'movies' AND COLUMN_NAME = 'POSTER_PATH_PT') = 0,
  'ALTER TABLE movies ADD COLUMN POSTER_PATH_PT TEXT',
  'ALTER TABLE movies MODIFY COLUMN POSTER_PATH_PT TEXT'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'movies' AND COLUMN_NAME = 'BACKDROP_PATH_PT') = 0,
  'ALTER TABLE movies ADD COLUMN BACKDROP_PATH_PT TEXT',
  'ALTER TABLE movies MODIFY COLUMN BACKDROP_PATH_PT TEXT'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
