ALTER TABLE movies ADD COLUMN MOVIE_NAME_PT VARCHAR(500);
ALTER TABLE movies ADD COLUMN OVERVIEW_PT TEXT;
ALTER TABLE movies ADD COLUMN TAGLINE_PT VARCHAR(500);
ALTER TABLE movies ADD COLUMN POSTER_PATH_PT VARCHAR(500);
ALTER TABLE movies ADD COLUMN BACKDROP_PATH_PT VARCHAR(500);
