package fast.campus.netplix.controller.camping;

import fast.campus.netplix.camping.CampingSite;

/**
 * 프론트엔드 전달용 야영장 DTO (GoCamping).
 */
public record CampingSiteResponse(
        String id,
        String name,
        String address,
        String zipcode,
        Double latitude,
        Double longitude,
        String induty,
        String lctCl,
        String shortIntro,
        String longIntro,
        String imageUrl,
        String tel,
        String homepage,
        String direction,
        String doNm,
        String sigunguNm,
        Double distanceKm,
        Integer gnrlSiteCo,
        Integer autoSiteCo,
        Integer glampSiteCo,
        Integer caravSiteCo,
        Integer indvdlCaravSiteCo,
        Integer sitedStncCo,
        Integer toiletCo,
        Integer swrmCo,
        Integer wpcfcCo,
        Integer extshrCo,
        Integer frprvtWrppCo,
        Integer frprvtSandCo,
        Integer fireSensorCo,
        String sbrsCl,
        String sbrsEtc,
        String posblFcltyCl,
        String themaEnvrnCl,
        String brazierCl,
        String eqpmnLendCl,
        String animalCmgCl
) {
    public static CampingSiteResponse from(CampingSite s) {
        return new CampingSiteResponse(
                s.getId(),
                s.getName(),
                s.getAddress(),
                s.getZipcode(),
                s.getLatitude(),
                s.getLongitude(),
                s.getInduty(),
                s.getLctCl(),
                s.getShortIntro(),
                s.getLongIntro(),
                s.getImageUrl(),
                s.getTel(),
                s.getHomepage(),
                s.getDirection(),
                s.getDoNm(),
                s.getSigunguNm(),
                s.getDistanceKm(),
                s.getGnrlSiteCo(),
                s.getAutoSiteCo(),
                s.getGlampSiteCo(),
                s.getCaravSiteCo(),
                s.getIndvdlCaravSiteCo(),
                s.getSitedStncCo(),
                s.getToiletCo(),
                s.getSwrmCo(),
                s.getWpcfcCo(),
                s.getExtshrCo(),
                s.getFrprvtWrppCo(),
                s.getFrprvtSandCo(),
                s.getFireSensorCo(),
                s.getSbrsCl(),
                s.getSbrsEtc(),
                s.getPosblFcltyCl(),
                s.getThemaEnvrnCl(),
                s.getBrazierCl(),
                s.getEqpmnLendCl(),
                s.getAnimalCmgCl()
        );
    }
}
